# mysql connect configuration
mysql:
    username: sgnbs
    password: 'Chinavnet.1'
    path: '192.168.11.199:3306'
    db-name: 'imooc'
    config: 'charset=utf8&parseTime=True&loc=Local'
    max-idle-conns: 10
    max-open-conns: 10
    log-mode: false


# system configuration
system:
    use-multipoint: false
    env: 'public'  # Change to "develop" to skip authentication for development mode
    addr: 8888
    db-type: "mysql"  # support mysql/sqlite

# captcha configuration
captcha:
    key-long: 4
    img-width: 120
    img-height: 40

# logger configuration
log:
    prefix: '[GO-Master]'
    log-file: true
    stdout: 'DEBUG'
    file: 'DEBUG'
