info:
  contact: {}
  license: {}
paths:
  /product/{id}:
    get:
      parameters:
      - description: 产品信息id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 产品信息
      tags:
      - Base
swagger: "2.0"
